# infra/traefik.yml — Traefik reverse proxy konfiguratsiyasi

api:
  dashboard: true
  insecure:  false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to:     websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

providers:
  docker:
    endpoint:        "unix:///var/run/docker.sock"
    exposedByDefault: false
    network:         alone-network

certificatesResolvers:
  letsencrypt:
    acme:
      email:   admin@aloneai.uz
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web